base_dir: "workspaces"
prompt: "default"

# Agent-specific directory structure
agent_directories:
  - name: "agent"
    permissions: "rw"      # Own agent code
    other_agents: "ro"      # Other agents can read code

# Shared resources at workspace root
shared_directories:
  - name: "tasks"
    permissions: "ro"

  - name: "tools"
    permissions: "ro" 

  - name: "blog"
    permissions: "rw"

tools:
  - name: "task_runner"

