base_dir: "workspaces"
prompt: "usaco"

# Agent-specific directory structure
agent_directories:
  - name: "agent"
    permissions: "rw"      # Own agent code
    other_agents: "ro"      # Other agents can read code

# Shared resources at workspace root
shared_directories:

